{
 "title": "Air Quality - Particulate Matter",
 "time": { "from": "now-20m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device_name",
    "label": "Device",
    "query": "{\n            \"request\": \"AttributeValue\",\n            \"fiwareScope\": {\n                \"service\": \"$service\",\n                \"servicePath\": \"$servicepath\",\n                \"type\": \"$type\"\n            },\n            \"entityId\": \"All\",\n            \"attributeName\": \"name\" }"
   },
   {
    "name": "device_selected",
    "query": "        {\n            \"request\": \"Entities\",\n            \"fiwareScope\": {\n                \"service\": \"$service\",\n                \"servicePath\": \"$servicepath\",\n                \"type\": \"$type\"\n            },\n            \"attributeName\": \"id,name\",\n            \"queryFilter\": \"name=='$device_name'\",\n            \"executePostQueryFilter\": true\n        }"
   },
   { "name": "service", "query": "AirQuality" },
   { "name": "servicepath", "query": "/data" },
   { "name": "type", "query": "AirQualityObserved" },
   {
    "name": "table",
    "query": "mtairquality.etairqualityobserved"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<style>\n\n.dashboard-header {\n  background: #0971b8;\n  width: 100%;\n  height: 120px;\n  font-family: \"Arial\"!important;\n  font-weight: 700!important;\n  text-align: left\n}\n\n.dashboard-header-left {\n  width: calc(100% - 450px);\n  height: 120px;\n  float: left;\n}\n\n.dashboard-header-right {\n  width: 450px;\n  height: 120px;\n  float: right;\n  background: #fff;\n  text-align: center;\n}\n\n.dashboard-header-right img {\n  height: 100px;\n  width: auto;\n  margin: 10px auto;\n}\n\n.dashboard-header-left-left {\n  width: calc(100% - 250px);\n  height: 120px;\n  float: left;\n}\n\n.dashboard-header-left-right {\n  width: 250px;\n  height: 120px;\n  float: right;\n}\n\n.dashboard-title {\n  width: 100%;\n  height: 120px;\n}\n\n.dashboard-subtitle {\n  width: 100%;\n  height: 40px;\n}\n\n.dashboard-title h1 {\n  margin: 5px 0 0 20px;\n  color: #fff;\n  font-size: 48px;\n  line-height: 120px;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  white-space: nowrap;\n  float: left;\n}\n\n.dashboard-subtitle span {\n  margin: 0 0 0 20px;\n  color: #fff;\n  display: block;\n  font-family: 'Roboto',Helvetica Neue,Arial,sans-serif;\n  font-size: 16px;\n  line-height: 30px;\n  border: none !important;\n  padding: 0 !important;\n}\n  \n.back-container-text {\n  height: 120px;\n  width: calc(100% - 70px);\n  text-align: right;\n  float: left;\n  font-family: 'Roboto',Helvetica Neue,Arial,sans-serif;\n  font-size: 16px;\n}\n\n.back-container-text h5 {\n  line-height: 120px;\n  color: #fff;\n}\n\n.back-container-icon {\n  width: 50px;\n  height: 50px;\n  background: #fff;\n  border-radius: 50%;\n  text-align: center;\n  float: right;\n  margin: 35px 10px;\n  transition: 0.3s ease all;\n}\n  \n.back-container-icon span {\n  height: 20px;\n  width: auto;\n  line-height: 37px;\n  transition: 0.3s ease all;\n}\n  \na:hover .back-container-icon {\n  background: #edac15;\n}\n\n@media screen and (max-width: 720px) {\n  .dashboard-header-left, .dashboard-header-right {\n    width: 100%;\n    height: 60px;\n    float: none;\n  }\n  \n  .dashboard-header-right img {\n    height: 50px;\n    margin: 5px auto;\n  }\n\n  .dashboard-header-left-left {\n    height: 60px;\n  }\n\n  .dashboard-header-left-right {\n    height: 60px;\n  }\n  \n  .dashboard-title {\n    height: 60px;\n  }\n\n  .dashboard-title h1 {\n    line-height: 60px;\n    font-size: 32px;\n    margin: 5px 0 0 10px;\n  }\n  \n  .back-container-text {\n    height: 60px;\n    display: none;\n  }\n\n  .back-container-text h5 {\n    line-height: 60px;\n  }\n  \n  .back-container-icon {\n    width: 30px;\n    height: 30px;\n    margin: 20px 10px;\n  }\n  \n  .back-container-icon span {\n    line-height: 17px;\n  }\n  \n  .mapcontainer {\n    width: calc(100% - 40px);\n    margin: auto;\n  }\n  \n}\n\n</style>\n\n  <div class=\"dashboard-header\">\n    <div class=\"dashboard-header-left\">\n      <div class=\"dashboard-header-left-left\">\n        <div class=\"dashboard-title\">\n          <h1 style=\"font-weight: 700\">\n            AIR QUALITY - PARTICULATE MATTER\n          </h1>\n        </div>\n      </div>\n      <a href=\"/d/aqapp-home\">\n        <div class=\"dashboard-header-left-right\">\n          <div class=\"back-container-text\">\n          </div>\n          <div class=\"back-container-icon\">\n            <span class=\"fa fa-chevron-left\"></span>\n          </div>\n        </div>\n      </a>\n    </div>\n    <div class=\"dashboard-header-right\">\n      <a href=\"https://hopu.eu/\" target=\"_blank\">\n        <img src=\"https://seeklogo.com/images/D/Dublin_City_Council-logo-4852E9EA38-seeklogo.com.png\">\n      <a>\n    </div>\n  </div\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "options": {
    "content": "**Dispositivo seleccionado:** $device_name\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 4 },
   "options": {
    "content": "<div style=\"accent-color: auto;align-content: normal;align-items: normal;align-self: auto;animation-delay: 0s;animation-direction: normal;animation-duration: 0s;animation-fill-mode: none;animation-iteration-count: 1;animation-name: none;animation-play-state: running;animation-timing-function: ease;appearance: none;aspect-ratio: auto;backface-visibility: visible;background-attachment: scroll;background-blend-mode: normal;background-clip: border-box;background-color: rgba(255, 255, 255, 0.8);background-image: none;background-origin: padding-box;background-position-x: 0%;background-position-y: 0%;background-repeat: repeat;background-size: auto;block-size: 120px;border-block-end-color: rgb(85, 85, 85);border-block-end-style: none;border-block-end-width: 0px;border-block-start-color: rgb(85, 85, 85);border-block-start-style: none;border-block-start-width: 0px;border-bottom-color: rgb(85, 85, 85);border-bottom-left-radius: 5px;border-bottom-right-radius: 5px;border-bottom-style: none;border-bottom-width: 0px;border-collapse: separate;border-end-end-radius: 5px;border-end-start-radius: 5px;border-image-outset: 0;border-image-repeat: stretch;border-image-slice: 100%;border-image-source: none;border-image-width: 1;border-inline-end-color: rgb(85, 85, 85);border-inline-end-style: none;border-inline-end-width: 0px;border-inline-start-color: rgb(85, 85, 85);border-inline-start-style: none;border-inline-start-width: 0px;border-left-color: rgb(85, 85, 85);border-left-style: none;border-left-width: 0px;border-right-color: rgb(85, 85, 85);border-right-style: none;border-right-width: 0px;border-spacing: 0px 0px;border-start-end-radius: 5px;border-start-start-radius: 5px;border-top-color: rgb(85, 85, 85);border-top-left-radius: 5px;border-top-right-radius: 5px;border-top-style: none;border-top-width: 0px;bottom: 0px;box-decoration-break: slice;box-shadow: rgba(0, 0, 0, 0.2) 0px 0px 15px 0px;box-sizing: border-box;break-after: auto;break-before: auto;break-inside: auto;caption-side: top;caret-color: rgb(85, 85, 85);clear: both;clip: auto;clip-path: none;clip-rule: nonzero;color: rgb(85, 85, 85);color-interpolation: srgb;color-interpolation-filters: linearrgb;color-scheme: normal;column-count: auto;column-fill: balance;column-gap: normal;column-rule-color: rgb(85, 85, 85);column-rule-style: none;column-rule-width: 0px;column-span: none;column-width: auto;contain: none;content: normal;counter-increment: none;counter-reset: none;counter-set: none;cursor: auto;cx: 0px;cy: 0px;d: none;direction: ltr;display: flex;dominant-baseline: auto;empty-cells: show;fill: rgb(0, 0, 0);fill-opacity: 1;fill-rule: nonzero;filter: none;flex-basis: auto;flex-direction: column;flex-grow: 0;flex-shrink: 1;flex-wrap: nowrap;float: left;flood-color: rgb(0, 0, 0);flood-opacity: 1;font-family: Arial, Helvetica, sans-serif;font-feature-settings: normal;font-kerning: auto;font-language-override: normal;font-optical-sizing: auto;font-size: 14px;font-size-adjust: none;font-stretch: 100%;font-style: normal;font-synthesis: weight style small-caps;font-variant-alternates: normal;font-variant-caps: normal;font-variant-east-asian: normal;font-variant-ligatures: normal;font-variant-numeric: normal;font-variant-position: normal;font-variation-settings: normal;font-weight: 400;grid-auto-columns: auto;grid-auto-flow: row;grid-auto-rows: auto;grid-column-end: auto;grid-column-start: auto;grid-row-end: auto;grid-row-start: auto;grid-template-areas: none;grid-template-columns: none;grid-template-rows: none;height: 120px;hyphenate-character: auto;hyphens: manual;image-orientation: from-image;image-rendering: auto;ime-mode: auto;inline-size: 195.2px;inset-block-end: 0px;inset-block-start: 0px;inset-inline-end: 0px;inset-inline-start: 0px;isolation: auto;justify-content: normal;justify-items: normal;justify-self: auto;left: 0px;letter-spacing: normal;lighting-color: rgb(255, 255, 255);line-break: auto;line-height: 18px;list-style-image: none;list-style-position: outside;list-style-type: disc;margin-block-end: 10px;margin-block-start: 0px;margin-bottom: 10px;margin-inline-end: 8px;margin-inline-start: 10px;margin-left: 10px;margin-right: 8px;margin-top: 0px;marker-end: none;marker-mid: none;marker-start: none;mask-clip: border-box;mask-composite: add;mask-image: none;mask-mode: match-source;mask-origin: border-box;mask-position-x: 0%;mask-position-y: 0%;mask-repeat: repeat;mask-size: auto;mask-type: luminance;max-block-size: none;max-height: none;max-inline-size: none;max-width: none;min-block-size: 0px;min-height: 0px;min-inline-size: 0px;min-width: 0px;mix-blend-mode: normal;object-fit: fill;object-position: 50% 50%;offset-anchor: auto;offset-distance: 0px;offset-path: none;offset-rotate: auto;opacity: 1;order: 0;outline-color: rgb(85, 85, 85);outline-offset: 0px;outline-style: none;outline-width: 0px;overflow-anchor: auto;overflow-block: visible;overflow-inline: visible;overflow-wrap: normal;overflow-x: visible;overflow-y: visible;overscroll-behavior-block: auto;overscroll-behavior-inline: auto;overscroll-behavior-x: auto;overscroll-behavior-y: auto;padding-block-end: 6px;padding-block-start: 6px;padding-bottom: 6px;padding-inline-end: 8px;padding-inline-start: 8px;padding-left: 8px;padding-right: 8px;padding-top: 6px;paint-order: normal;perspective: none;perspective-origin: 97.6px 60px;pointer-events: auto;position: relative;print-color-adjust: economy;quotes: auto;r: 0px;resize: none;right: 0px;rotate: none;row-gap: normal;ruby-align: space-around;ruby-position: alternate;rx: auto;ry: auto;scale: none;scroll-behavior: auto;scroll-margin-block-end: 0px;scroll-margin-block-start: 0px;scroll-margin-bottom: 0px;scroll-margin-inline-end: 0px;scroll-margin-inline-start: 0px;scroll-margin-left: 0px;scroll-margin-right: 0px;scroll-margin-top: 0px;scroll-padding-block-end: auto;scroll-padding-block-start: auto;scroll-padding-bottom: auto;scroll-padding-inline-end: auto;scroll-padding-inline-start: auto;scroll-padding-left: auto;scroll-padding-right: auto;scroll-padding-top: auto;scroll-snap-align: none;scroll-snap-type: none;scrollbar-color: auto;scrollbar-gutter: auto;scrollbar-width: auto;shape-image-threshold: 0;shape-margin: 0px;shape-outside: none;shape-rendering: auto;stop-color: rgb(0, 0, 0);stop-opacity: 1;stroke: none;stroke-dasharray: none;stroke-dashoffset: 0px;stroke-linecap: butt;stroke-linejoin: miter;stroke-miterlimit: 4;stroke-opacity: 1;stroke-width: 1px;tab-size: 8;table-layout: auto;text-align: start;text-align-last: auto;text-anchor: start;text-combine-upright: none;text-decoration-color: rgb(85, 85, 85);text-decoration-line: none;text-decoration-skip-ink: auto;text-decoration-style: solid;text-decoration-thickness: auto;text-emphasis-color: rgb(85, 85, 85);text-emphasis-position: over right;text-emphasis-style: none;text-indent: 0px;text-justify: auto;text-orientation: mixed;text-overflow: clip;text-rendering: auto;text-shadow: none;text-transform: none;text-underline-offset: auto;text-underline-position: auto;top: 0px;touch-action: auto;transform: none;transform-box: border-box;transform-origin: 97.6px 60px;transform-style: flat;transition-delay: 0s;transition-duration: 0s;transition-property: all;transition-timing-function: ease;translate: none;unicode-bidi: isolate;user-select: auto;vector-effect: none;vertical-align: baseline;visibility: visible;white-space: normal;width: 195.2px;will-change: auto;word-break: normal;word-spacing: 0px;writing-mode: horizontal-tb;x: 0px;y: 0px;z-index: 800;-moz-box-align: stretch;-moz-box-direction: normal;-moz-box-flex: 0;-moz-box-ordinal-group: 1;-moz-box-orient: horizontal;-moz-box-pack: start;-moz-float-edge: content-box;-moz-force-broken-image-icon: 0;-moz-image-region: auto;-moz-orient: inline;-moz-text-size-adjust: auto;-moz-user-focus: none;-moz-user-input: auto;-moz-user-modify: read-only;-moz-window-dragging: default;-webkit-line-clamp: none;-webkit-text-fill-color: rgb(85, 85, 85);-webkit-text-stroke-color: rgb(85, 85, 85);-webkit-text-stroke-width: 0px;\">\n<div style=\"box-sizing: border-box;color: rgb(85, 85, 85);cursor: auto;font-family: Arial, Helvetica, sans-serif;font-feature-settings: normal;font-kerning: auto;font-language-override: normal;font-optical-sizing: auto;font-size: 14px;font-size-adjust: none;font-stretch: 100%;font-style: normal;font-variant-alternates: normal;font-variant-caps: normal;font-variant-east-asian: normal;font-variant-ligatures: normal;font-variant-numeric: normal;font-variant-position: normal;font-variation-settings: normal;font-weight: 400;line-height: 18px;pointer-events: auto;white-space: nowrap;\"><i style=\"background-attachment: scroll;background-clip: border-box;background-color: rgba(0, 255, 250, 0.6);background-image: none;background-origin: padding-box;background-position-x: 0%;background-position-y: 0%;background-repeat: repeat;background-size: auto;box-sizing: border-box;color: rgb(85, 85, 85);cursor: auto;float: left;font-family: Arial, Helvetica, sans-serif;font-feature-settings: normal;font-kerning: auto;font-language-override: normal;font-optical-sizing: auto;font-size: 14px;font-size-adjust: none;font-stretch: 100%;font-style: italic;font-variant-alternates: normal;font-variant-caps: normal;font-variant-east-asian: normal;font-variant-ligatures: normal;font-variant-numeric: normal;font-variant-position: normal;font-variation-settings: normal;font-weight: 400;height: 18px;line-height: 18px;margin-left: 10px;margin-right: 10px;opacity: 0.7;pointer-events: auto;white-space: nowrap;width: 18px;\"></i> Good</div>\n<div class=\"box-sizing: border-box;color: rgb(85, 85, 85);cursor: auto;font-family: Arial, Helvetica, sans-serif;font-feature-settings: normal;font-kerning: auto;font-language-override: normal;font-optical-sizing: auto;font-size: 14px;font-size-adjust: none;font-stretch: 100%;font-style: normal;font-variant-alternates: normal;font-variant-caps: normal;font-variant-east-asian: normal;font-variant-ligatures: normal;font-variant-numeric: normal;font-variant-position: normal;font-variation-settings: normal;font-weight: 400;line-height: 18px;pointer-events: auto;white-space: nowrap;\"><i style=\"background-attachment: scroll;background-clip: border-box;background-color: rgba(80, 200, 163, 0.6);background-image: none;background-origin: padding-box;background-position-x: 0%;background-position-y: 0%;background-repeat: repeat;background-size: auto;box-sizing: border-box;color: rgb(85, 85, 85);cursor: auto;float: left;font-family: Arial, Helvetica, sans-serif;font-feature-settings: normal;font-kerning: auto;font-language-override: normal;font-optical-sizing: auto;font-size: 14px;font-size-adjust: none;font-stretch: 100%;font-style: italic;font-variant-alternates: normal;font-variant-caps: normal;font-variant-east-asian: normal;font-variant-ligatures: normal;font-variant-numeric: normal;font-variant-position: normal;font-variation-settings: normal;font-weight: 400;height: 18px;line-height: 18px;margin-left: 10px;margin-right: 10px;opacity: 0.7;pointer-events: auto;white-space: nowrap;width: 18px;\"></i>Fair</div>\n<div class=\"box-sizing: border-box;color: rgb(85, 85, 85);cursor: auto;font-family: Arial, Helvetica, sans-serif;font-feature-settings: normal;font-kerning: auto;font-language-override: normal;font-optical-sizing: auto;font-size: 14px;font-size-adjust: none;font-stretch: 100%;font-style: normal;font-variant-alternates: normal;font-variant-caps: normal;font-variant-east-asian: normal;font-variant-ligatures: normal;font-variant-numeric: normal;font-variant-position: normal;font-variation-settings: normal;font-weight: 400;line-height: 18px;pointer-events: auto;white-space: nowrap;\"><i style=\"background-attachment: scroll;background-clip: border-box;background-color: rgba(235, 235, 54, 0.6);background-image: none;background-origin: padding-box;background-position-x: 0%;background-position-y: 0%;background-repeat: repeat;background-size: auto;box-sizing: border-box;color: rgb(85, 85, 85);cursor: auto;float: left;font-family: Arial, Helvetica, sans-serif;font-feature-settings: normal;font-kerning: auto;font-language-override: normal;font-optical-sizing: auto;font-size: 14px;font-size-adjust: none;font-stretch: 100%;font-style: italic;font-variant-alternates: normal;font-variant-caps: normal;font-variant-east-asian: normal;font-variant-ligatures: normal;font-variant-numeric: normal;font-variant-position: normal;font-variation-settings: normal;font-weight: 400;height: 18px;line-height: 18px;margin-left: 10px;margin-right: 10px;opacity: 0.7;pointer-events: auto;white-space: nowrap;width: 18px;\"></i>Moderate</div>\n<div class=\"box-sizing: border-box;color: rgb(85, 85, 85);cursor: auto;font-family: Arial, Helvetica, sans-serif;font-feature-settings: normal;font-kerning: auto;font-language-override: normal;font-optical-sizing: auto;font-size: 14px;font-size-adjust: none;font-stretch: 100%;font-style: normal;font-variant-alternates: normal;font-variant-caps: normal;font-variant-east-asian: normal;font-variant-ligatures: normal;font-variant-numeric: normal;font-variant-position: normal;font-variation-settings: normal;font-weight: 400;line-height: 18px;pointer-events: auto;white-space: nowrap;\"><i style=\"background-attachment: scroll;background-clip: border-box;background-color: rgba(255, 79, 92, 0.6);background-image: none;background-origin: padding-box;background-position-x: 0%;background-position-y: 0%;background-repeat: repeat;background-size: auto;box-sizing: border-box;color: rgb(85, 85, 85);cursor: auto;float: left;font-family: Arial, Helvetica, sans-serif;font-feature-settings: normal;font-kerning: auto;font-language-override: normal;font-optical-sizing: auto;font-size: 14px;font-size-adjust: none;font-stretch: 100%;font-style: italic;font-variant-alternates: normal;font-variant-caps: normal;font-variant-east-asian: normal;font-variant-ligatures: normal;font-variant-numeric: normal;font-variant-position: normal;font-variation-settings: normal;font-weight: 400;height: 18px;line-height: 18px;margin-left: 10px;margin-right: 10px;opacity: 0.7;pointer-events: auto;white-space: nowrap;width: 18px;\"></i>Poor</div>\n<div class=\"box-sizing: border-box;color: rgb(85, 85, 85);cursor: auto;font-family: Arial, Helvetica, sans-serif;font-feature-settings: normal;font-kerning: auto;font-language-override: normal;font-optical-sizing: auto;font-size: 14px;font-size-adjust: none;font-stretch: 100%;font-style: normal;font-variant-alternates: normal;font-variant-caps: normal;font-variant-east-asian: normal;font-variant-ligatures: normal;font-variant-numeric: normal;font-variant-position: normal;font-variation-settings: normal;font-weight: 400;line-height: 18px;pointer-events: auto;white-space: nowrap;\"><i style=\"background-attachment: scroll;background-clip: border-box;background-color: rgba(192, 0, 0, 0.6);background-image: none;background-origin: padding-box;background-position-x: 0%;background-position-y: 0%;background-repeat: repeat;background-size: auto;box-sizing: border-box;color: rgb(85, 85, 85);cursor: auto;float: left;font-family: Arial, Helvetica, sans-serif;font-feature-settings: normal;font-kerning: auto;font-language-override: normal;font-optical-sizing: auto;font-size: 14px;font-size-adjust: none;font-stretch: 100%;font-style: italic;font-variant-alternates: normal;font-variant-caps: normal;font-variant-east-asian: normal;font-variant-ligatures: normal;font-variant-numeric: normal;font-variant-position: normal;font-variation-settings: normal;font-weight: 400;height: 18px;line-height: 18px;margin-left: 10px;margin-right: 10px;opacity: 0.7;pointer-events: auto;white-space: nowrap;width: 18px;\"></i>Very poor</div>\n<div class=\"box-sizing: border-box;color: rgb(85, 85, 85);cursor: auto;font-family: Arial, Helvetica, sans-serif;font-feature-settings: normal;font-kerning: auto;font-language-override: normal;font-optical-sizing: auto;font-size: 14px;font-size-adjust: none;font-stretch: 100%;font-style: normal;font-variant-alternates: normal;font-variant-caps: normal;font-variant-east-asian: normal;font-variant-ligatures: normal;font-variant-numeric: normal;font-variant-position: normal;font-variation-settings: normal;font-weight: 400;line-height: 18px;pointer-events: auto;white-space: nowrap;\"><i style=\"background-attachment: scroll;background-clip: border-box;background-color: rgba(153, 0, 255,0.6);background-image: none;background-origin: padding-box;background-position-x: 0%;background-position-y: 0%;background-repeat: repeat;background-size: auto;box-sizing: border-box;color: rgb(85, 85, 85);cursor: auto;float: left;font-family: Arial, Helvetica, sans-serif;font-feature-settings: normal;font-kerning: auto;font-language-override: normal;font-optical-sizing: auto;font-size: 14px;font-size-adjust: none;font-stretch: 100%;font-style: italic;font-variant-alternates: normal;font-variant-caps: normal;font-variant-east-asian: normal;font-variant-ligatures: normal;font-variant-numeric: normal;font-variant-position: normal;font-variation-settings: normal;font-weight: 400;height: 18px;line-height: 18px;margin-left: 10px;margin-right: 10px;opacity: 0.7;pointer-events: auto;white-space: nowrap;width: 18px;\"></i>Extremely poor</div>\n</div>\n\n"
   }
  },
  {
   "type": "geomap",
   "gridPos": { "h": 17, "w": 16, "x": 8, "y": 4 },
   "targets": [
    {
     "attributes": "All",
     "entityId": "All",
     "entityType": "All",
     "selectedRequest": "Entities",
     "service": "$service",
     "servicePath": "$servicepath",
     "target": "select metric",
     "type": "table"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time_index,'1h'),\n  avg(pm1) as \"PM1\"\nFROM\n   ${table:raw} \nWHERE\n  $__timeFilter(time_index) and entity_id = '$device_selected'\nGROUP BY 1\nORDER BY 1 ASC\n"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time_index,'1h'),\n  avg(pm25) as \"PM2.5\"\nFROM\n   ${table:raw}\nWHERE\n  $__timeFilter(time_index) and entity_id = '$device_selected'\nGROUP BY 1\nORDER BY 1 ASC\n"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time_index,'1h'),\n  avg(pm10) as \"PM10\"\nFROM\n   ${table:raw}\nWHERE\n  $__timeFilter(time_index) and entity_id = '$device_selected'\nGROUP BY 1\nORDER BY 1 ASC"
    }
   ]
  },
  { "title": "Show details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "PM1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time_index,'1h'),\n  avg(pm1) as \"PM1 hourly average\"\nFROM\n   ${table:raw} \nWHERE\n  $__timeFilter(time_index) and entity_id = '$device_selected'\nGROUP BY 1\nORDER BY 1 ASC\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(time_index,'1h'),\n  max(pm1) as \"PM1 hourly max\"\nFROM\n   ${table:raw} \nWHERE\n  $__timeFilter(time_index) and entity_id = '$device_selected'\nGROUP BY 1\nORDER BY 1 ASC\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(time_index,'1d'),\n  avg(pm1) as \"PM1 daily average\"\nFROM\n   ${table:raw} \nWHERE\n  $__timeFilter(time_index) and entity_id = '$device_selected'\nGROUP BY 1\nORDER BY 1 ASC\n"
    }
   ]
  },
  {
   "title": "PM2.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time_index,'1h'),\n  avg(pm25) as \"PM2.5 hourly average\"\nFROM\n   ${table:raw} \nWHERE\n  $__timeFilter(time_index) and entity_id = '$device_selected'\nGROUP BY 1\nORDER BY 1 ASC\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(time_index,'1h'),\n  max(pm25) as \"PM2.5 hourly max\"\nFROM\n   ${table:raw} \nWHERE\n  $__timeFilter(time_index) and entity_id = '$device_selected'\nGROUP BY 1\nORDER BY 1 ASC\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(time_index,'1d'),\n  avg(pm25) as \"PM2.5 daily average\"\nFROM\n   ${table:raw} \nWHERE\n  $__timeFilter(time_index) and entity_id = '$device_selected'\nGROUP BY 1\nORDER BY 1 ASC\n"
    }
   ]
  },
  {
   "title": "PM10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time_index,'1h'),\n  avg(pm10) as \"PM10 hourly average\"\nFROM\n   ${table:raw} \nWHERE\n  $__timeFilter(time_index) and entity_id = '$device_selected'\nGROUP BY 1\nORDER BY 1 ASC\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(time_index,'1h'),\n  max(pm10) as \"PM10 hourly max\"\nFROM\n   ${table:raw} \nWHERE\n  $__timeFilter(time_index) and entity_id = '$device_selected'\nGROUP BY 1\nORDER BY 1 ASC\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(time_index,'1d'),\n  avg(pm10) as \"PM10 daily average\"\nFROM\n   ${table:raw} \nWHERE\n  $__timeFilter(time_index) and entity_id = '$device_selected'\nGROUP BY 1\nORDER BY 1 ASC\n"
    }
   ]
  },
  {
   "title": "Particulate matter comparative",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Particulate matter comparative",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "conμgm3" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroup(time_index,'1h'),\n  avg(pm1) as \"PM1 hourly average\",\n  avg(pm25) as \"PM2.5 hourly average\",\n  avg(pm10) as \"PM10 hourly average\"\nFROM\n   ${table:raw} \nWHERE\n  $__timeFilter(time_index) and entity_id = '$device_selected'\nGROUP BY 1\nORDER BY 1 ASC\n\n"
      }
     ]
    }
   ]
  }
 ]
}